### ISSUE TITLE
Spec it!

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/now-fleet#1]
what do we want?

- a way to easy deploy a 'fleet' of microservices

 ```javascript
{
   services: {
      cruiser: "^2.0.0",
      destroyer: "^1.0.0"
    }
}
```

cruiser
 ```javascript
{
   services: {
      lifeboat: "^1.0.0"
    }
}
```

**Comment by mstdokumaci** [comment]
### Background
To deploy an NPM module through API, you need to create a JSON including every file in the module. CLI tool of now does all the hard work of packing the JSON and sending but it's not open sourced. Requiring & reusing is a very tricky way to waste time.

### Proposal
We can use the CLI tool instead and parse the console output by scripting. Basic dependency installing might be implemented like following.
For  each service dependency:
- npm install service@version
- now node_modules/service > output.txt
- parse url from output.txt & add to JSON object in `services.js` with service name as key.

### Challenges
- CLI tool works with authentication, which requires interactive typing of email. Should be mimicked by script or `~/now.json` should be provided with credentials.
- Circular service dependencies will cause an endless deploy cycle. Solving this is tricky because neither `now ls` nor API call to `GET /now/deployments` provides us a version number for deployed modules; just a hash of all the code & package.json which we can't check locally unless we discover how now CLI tool generates the hash.

**Comment by jimdebeer** [comment]
For the challenges -- now supports api-tokens -- so you can setup an environment variable (I think its now token or something) this also works in `travis-ci` (you can access it since you are part of the vigour team)

Rather then using the output.txt I would add an `_services:` field in the package, and keep the rest in memory (using spawn), its a similar approach as the npm package for shared dependencies (they add many _ fields)

The reason I would like this in the package, is that our front ends already require the `package.json` (so routing can be done straight from the package)

@youzi what do you think?

**Comment by jimdebeer** [comment]
@mstdokumaci maybe im wrong here? But seems really close to having a `services.js` right?

**Comment by mstdokumaci** [comment]
@jimdebeer If `package.json`is already used, then it looks like the best choice to me. I'll try my chance with npm now library today. Because I don't want to spec anything before I have some proof of concept.

**Comment by jimdebeer** [comment]
ok man! Today they are launching private npm so we will actually start using it! ;)

**Comment by mstdokumaci** [comment]
# Background
We have this app hosting service `now`, which provides us easy CLI deployment of any folder with a `package.json` and returns a url for https access. It also has an API to check our existing deployments & send new ones. Unlike npm, we can send a new deployment without updating version number in `package.json`. It generates a hash of actual folder and uploads a new deployment whenever a file changes in the folder. So we can have two different deployments for same version of an npm module, both of which might not even be published to npm. That's why we can't depend on `now` hashes. Because our microservices depend on each other using npm semver. So we'll depend on npm versions.

# Implementation

## Basic Structure
We will define dependencies of each microservice in the `package.json` and expect to find deployment urls in `package.json` after running this `now-fleet` tool. Example `package.json` of npm module `fleet` before deployment will be like:
```json
{
  "name": "fleet",
  "version": "2.1.1",
  "devDependencies": {
    "now-fleet": "^1.0.0"
  },
  "services": {
    "cruiser": "^2.0.0",
    "destroyer": "^1.0.0"
  }
}
```

After deployment, live version of `package.json` will be like:
```json
{
  "name": "fleet",
  "version": "2.1.1",
  "devDependencies": {
    "now-fleet": "^1.0.0"
  },
  "services": {
    "cruiser": "^2.0.0",
    "destroyer": "^1.0.0"
  },
  "_services": {
    "cruiser": "https://cruiser-now-url.sh",
    "destroyer": "https://destroyer-now-url.sh"
  }
}
```

## Usage
`now-fleet` provides a CLI script similar to now. In the folder of npm module you run `now-fleet` and it deploys the whole stack.
**Assumption**: We add now-fleet to start script of every microservice so deployment of root service starts the chain of deployments.
```json
{
  "scripts": {
    "start": "npm run now-fleet && npm test && node index.js",
    "now-fleet": "node_modules/.bin/now-fleet"
  }
}
```

## Basic flow of `now-fleet` script

1) Read `services` object from `package.json` in the folder. Let's say it's like:
```json
{
  "cruiser": "^2.0.0",
  "destroyer": "^1.0.0"
}
```
2) Initialize a `_services` object for `package.json` in the folder.
```js
let _services = {};
```
3) Get deployed services list from now API.
```json
{
  "deployments": [
    {
      "uid": "7Npest0z1zW5QVFfNDBId4BW",
        "name": "fleet",
        "url": "fleet-bfzfxvjaewj.now.sh",
        "created": "1460801613968"
    },
    {
      "uid": "dOgCUIoovYiYmXbrLX0h9qDk",
      "name": "cruiser",
      "url": "cruiser-iipihlfrpa.now.sh",
      "created": "1462738579605"
    },
    {
      "uid": "dOgCUIoovYJYmXbrLX0h9qDk",
      "name": "cruiser",
      "url": "cruiser-bfzfxvjaewl.now.sh",
      "created": "1462738599605"
    }
  ]
}
```
4) Iterate through `services` object from `package.json` in the folder. For each service:
4.1) Run `nmp v module@semver version` and get latest version from output. Let's say for `nmp v cruiser@^2.0.0 version` we find version `2.0.5`
4.2) Iterate through deployed services list and try finding that latest version by reading `package.json` of deployments. For our example, filter deployments of cruiser and read version from `package.json` from each and compare to `2.0.5`
4.3) If latest version found in deployments, set found url for service key in `_services` object. Skip next step and continue iteration. Let's say url for `cruiser@2.0.5` is `https://cruiser-bfzfxvjaewl.now.sh`
4.4) If latest version was not found in deployments:
4.4.1) Run `npm install module@semver`. For our example: `npm install cruiser@^2.0.0`
4.4.2) Switch to `node_modules/module/` and run `now`.
4.4.3) Get deployment url from output of `now` and set url for service key in `_services` object.
5) Write `_services` object in `package.json` in the folder.

**Comment by mstdokumaci** [comment]
Now I found a flaw in this approach above. This one checks for each service, if any dependency has an update which fits own semver and if so, re-deploys that dependency. But it's unaware if dependency of dependency was updated and dependency needs to be re-deployed just because of that.

Design needs to be changed in a way, one script for walking through everything and figuring out what to re-deploy. Another script to run before start and discover urls of right versions for dependencies and adjust _services accordingly.

**Comment by mstdokumaci** [comment]
# New approach of 2 CLI scripts

We'll have 2 CLI scripts for deployment.
1. Runs before deploying anything and decides which services need a re-deploy.
2. Runs after deployment of each microservice and auto-discovers latest deployed dependencies.

Let's call 1st one `now-fleet-deploy` and second one `now-fleet-discover`

## now-fleet-deploy
This one will do the hard job. It'll walk through all the tree and trigger deployment of necessary ones.
It'll create an array of microservices like:
```js
services_flat = [
  {
    "name": "service-name",
    "version": "1.2.2",
    "dependencies": [], // references to service objects in this array
    "dependants": [], // references to service objects in this array
    "deploy": true, // needs to be re-deployed
    "last_deploy": "timestamp",
    "last_url": "https://now-deployment-url.sh"
  }
]
```
We will collect data for this array from npm and now API.

`npm v service-name@^1.0.0 versions` returns a list of versions which fits to requirement. We take the latest one and ask for dependencies using `npm v service-name@1.2.2 services`, which returns services object from `package.json` of queried module.

From now API, we can query every running deployment and get package.json of each. So we can match them with services in the array and set fields `last_deploy` and `last_url`. When we find a module in this array, has no deployment of required version, then we'll mark it as `deploy: true`. We'll mark every dependant of it `deploy: true` recursively.

For deployment, script will iterate through the array it created and `npm install` each module with `deploy: true`. Then it'll add `_services` object to `package.json`. For dependencies `deploy: false`, it'll copy the url from `dependency.last_url`. For dependencies `deploy: true`, it'll copy `dependency.last_deploy` timestamp instead of url. `_services` object will eventually look like:
```js
_services = {
  "service-one": 0, // never deployed before
  "service-two": 1469310816, // last deployment timestamp, will be re-deployed
  "service-three": "https://now-deployment-url.sh" // does not need to be re-deployed
}
```

### Limitations
This script should be run at the topmost level of tree. Which means the module where we run this script shouldn't have any dependant services or if it has, those dependants should be reachable by depdendencies (circular dependency).

## now-fleet-discover
This script will run on start of the service at now server. It'll try discovering urls for own dependencies by given `package.json` and deployments list from now API.

It'll get the list of deployments from now API. It'll check `_services` object for unknown urls and will try to find a new deployment of given version of given module, which has a bigger timestamp than `last_deploy`. If it can find urls for every dependency service, it'll quit. Otherwise it'll wait few seconds and retry after fetching list from now API.

**Comment by jimdebeer** [comment]
hey @mstdokumaci looks really thorough!, for nested dependencies we just need to load them from the top level (this way we can have nested deps -- probably good idea to keep track in memory of the deps tree so we dont end up with circular ones, this way you can even deploy circular ones by reusing the deps that are already launched (think require)

```
a
  -  b 
      -  c
           - b
```

c can just use a.b

**Comment by jimdebeer** [comment]
btw this is the repo for issues with now
https://github.com/zeit/now-issues/issues

**Comment by mstdokumaci** [comment]
@jimdebeer by having a flat array of every service in memory, circular dependencies are taken care of. This is now something to be implemented.

now API is enough for this implementation. Because we no longer need local hash generation. And for deployment we can just use now CLI.

For npm queries, I would like to use npm module programmatically, but it's not documented at all and developers of npm advice against. So we can use npm CLI as well.

**Comment by jimdebeer** [comment]
I think its pretty much specced!
